In [2]:
from sklearn.datasets import load_iris, fetch_20newsgroups, load_boston
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.feature_extraction import DictVectorizer
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score


In [10]:
li=load_iris()
print(type(li.data))
print(li.data.shape)
# print(li.DESCR)
print(li.feature_names)

<class 'numpy.ndarray'>
(150, 4)
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [16]:
x_train,x_test,y_train,y_test=train_test_split(li.data,li.target,train_size=.75,random_state=1)
print(x_train)
print(y_train)
print(x_train.shape)

[[6.5 2.8 4.6 1.5]
 [6.7 2.5 5.8 1.8]
 [6.8 3.  5.5 2.1]
 [5.1 3.5 1.4 0.3]
 [6.  2.2 5.  1.5]
 [6.3 2.9 5.6 1.8]
 [6.6 2.9 4.6 1.3]
 [7.7 2.6 6.9 2.3]
 [5.7 3.8 1.7 0.3]
 [5.  3.6 1.4 0.2]
 [4.8 3.  1.4 0.3]
 [5.2 2.7 3.9 1.4]
 [5.1 3.4 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [7.7 3.8 6.7 2.2]
 [6.9 3.1 5.4 2.1]
 [7.3 2.9 6.3 1.8]
 [6.4 2.8 5.6 2.2]
 [6.2 2.8 4.8 1.8]
 [6.  3.4 4.5 1.6]
 [7.7 2.8 6.7 2. ]
 [5.7 3.  4.2 1.2]
 [4.8 3.4 1.6 0.2]
 [5.7 2.5 5.  2. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.  1.4 0.1]
 [4.7 3.2 1.3 0.2]
 [6.5 3.  5.8 2.2]
 [4.6 3.4 1.4 0.3]
 [6.1 3.  4.9 1.8]
 [6.5 3.2 5.1 2. ]
 [6.7 3.1 4.4 1.4]
 [5.7 2.8 4.5 1.3]
 [6.7 3.3 5.7 2.5]
 [6.  3.  4.8 1.8]
 [5.1 3.8 1.6 0.2]
 [6.  2.2 4.  1. ]
 [6.4 2.9 4.3 1.3]
 [6.5 3.  5.5 1.8]
 [5.  2.3 3.3 1. ]
 [6.3 3.3 6.  2.5]
 [5.5 2.5 4.  1.3]
 [5.4 3.7 1.5 0.2]
 [4.9 3.1 1.5 0.2]
 [5.2 4.1 1.5 0.1]
 [6.7 3.3 5.7 2.1]
 [4.4 3.  1.3 0.2]
 [6.  2.7 5.1 1.6]
 [6.4 2.7 5.3 1.9]
 [5.9 3.  5.1 1.8]
 [5.2 3.5 1.5 0.2]
 [5.1 3.3 1.7 0.5]
 [5.8 2.7 4.

In [19]:
news=fetch_20newsgroups(subset='all',data_home='data')
print(news.DESCR)

.. _20newsgroups_dataset:

The 20 newsgroups text dataset
------------------------------

The 20 newsgroups dataset comprises around 18000 newsgroups posts on
20 topics split in two subsets: one for training (or development)
and the other one for testing (or for performance evaluation). The split
between the train and test set is based upon a messages posted before
and after a specific date.

This module contains two loaders. The first one,
:func:`sklearn.datasets.fetch_20newsgroups`,
returns a list of the raw texts that can be fed to text feature
extractors such as :class:`~sklearn.feature_extraction.text.CountVectorizer`
with custom parameters so as to extract feature vectors.
The second one, :func:`sklearn.datasets.fetch_20newsgroups_vectorized`,
returns ready-to-use features, i.e., it is not necessary to use a feature
extractor.

**Data Set Characteristics:**

    =================   ==========
    Classes                     20
    Samples total            18846
    Dimensionality

In [26]:
print(news.data[0])
print(len(news.data))
print(min(news.target),max(news.target))
print(news.target.shape)


From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>
Subject: Pens fans reactions
Organization: Post Office, Carnegie Mellon, Pittsburgh, PA
Lines: 12
NNTP-Posting-Host: po4.andrew.cmu.edu



I am sure some bashers of Pens fans are pretty confused about the lack
of any kind of posts about the recent Pens massacre of the Devils. Actually,
I am  bit puzzled too and a bit relieved. However, I am going to put an end
to non-PIttsburghers' relief with a bit of praise for the Pens. Man, they
are killing those Devils worse than I thought. Jagr just showed you why
he is much better than his regular season stats. He is also a lot
fo fun to watch in the playoffs. Bowman should let JAgr have a lot of
fun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final
regular season game.          PENS RULE!!!


18846
0 19
(18846,)


In [34]:
lb=load_boston()
print(lb.data[0])
# print(lb.DESCR)
print(lb.data.shape)
print(lb.target.shape)
# print(lb.target)
print(lb.feature_names)

[6.320e-03 1.800e+01 2.310e+00 0.000e+00 5.380e-01 6.575e+00 6.520e+01
 4.090e+00 1.000e+00 2.960e+02 1.530e+01 3.969e+02 4.980e+00]
(506, 13)
(506,)
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [36]:
data=pd.read_csv('./train.csv')
print(data.head(5))

   row_id       x       y  accuracy    time    place_id
0       0  0.7941  9.0809        54  470702  8523065625
1       1  5.9567  4.7968        13  186555  1757726713
2       2  8.3078  7.0407        74  322648  1137537235
3       3  7.3665  2.5165        65  704587  6567393236
4       4  4.0961  1.1307        31  472130  7440663949


MemoryError: Unable to allocate 889. MiB for an array with shape (4, 29118021) and data type int64

In [38]:
print(data.shape)
data=data.query("x>1.0&x<1.25&y>2.5&y<2.75")
print(data.shape)

(17710, 6)
(17710, 6)


In [41]:
time_value=pd.to_datetime(data['time'],unit='s')
print(time_value)


600        1970-01-01 18:09:40
957        1970-01-10 02:11:10
4345       1970-01-05 15:08:02
4735       1970-01-06 23:03:03
5580       1970-01-09 11:26:50
                   ...        
29100203   1970-01-01 10:33:56
29108443   1970-01-07 23:22:04
29109993   1970-01-08 15:03:14
29111539   1970-01-04 00:53:41
29112154   1970-01-08 23:01:07
Name: time, Length: 17710, dtype: datetime64[ns]


In [45]:
time_value=pd.DatetimeIndex(time_value)
print(time_value)
print(type(data))

DatetimeIndex(['1970-01-01 18:09:40', '1970-01-10 02:11:10',
               '1970-01-05 15:08:02', '1970-01-06 23:03:03',
               '1970-01-09 11:26:50', '1970-01-02 16:25:07',
               '1970-01-04 15:52:57', '1970-01-01 10:13:36',
               '1970-01-09 15:26:06', '1970-01-08 23:52:02',
               ...
               '1970-01-07 10:03:36', '1970-01-09 11:44:34',
               '1970-01-04 08:07:44', '1970-01-04 15:47:47',
               '1970-01-08 01:24:11', '1970-01-01 10:33:56',
               '1970-01-07 23:22:04', '1970-01-08 15:03:14',
               '1970-01-04 00:53:41', '1970-01-08 23:01:07'],
              dtype='datetime64[ns]', name='time', length=17710, freq=None)
<class 'pandas.core.frame.DataFrame'>


In [47]:
data.insert(data.shape[1],'day',time_value.day)
data.insert(data.shape[1],'hour',time_value.hour)
data.insert(data.shape[1],'weekday',time_value.weekday)

ValueError: cannot insert day, already exists

In [50]:
data=data.drop(['time'],axis=1)
print(data)


KeyError: "['time'] not found in axis"

In [53]:
place_count=data.groupby('place_id').count()
print(place_count)

            row_id     x     y  accuracy   day  hour  weekday
place_id                                                     
1012023972       1     1     1         1     1     1        1
1057182134       1     1     1         1     1     1        1
1059958036       3     3     3         3     3     3        3
1085266789       1     1     1         1     1     1        1
1097200869    1044  1044  1044      1044  1044  1044     1044
...            ...   ...   ...       ...   ...   ...      ...
9904182060       1     1     1         1     1     1        1
9915093501       1     1     1         1     1     1        1
9946198589       1     1     1         1     1     1        1
9950190890       1     1     1         1     1     1        1
9980711012       5     5     5         5     5     5        5

[805 rows x 7 columns]


In [55]:
tf=place_count[place_count.row_id>3].reset_index()
print(tf)

       place_id  row_id     x     y  accuracy   day  hour  weekday
0    1097200869    1044  1044  1044      1044  1044  1044     1044
1    1228935308     120   120   120       120   120   120      120
2    1267801529      58    58    58        58    58    58       58
3    1278040507      15    15    15        15    15    15       15
4    1285051622      21    21    21        21    21    21       21
..          ...     ...   ...   ...       ...   ...   ...      ...
234  9741307878       5     5     5         5     5     5        5
235  9753855529      21    21    21        21    21    21       21
236  9806043737       6     6     6         6     6     6        6
237  9809476069      23    23    23        23    23    23       23
238  9980711012       5     5     5         5     5     5        5

[239 rows x 8 columns]


In [57]:
data=data[data.place_id.isin(tf.place_id)]
print(data)

            row_id       x       y  accuracy    place_id  day  hour  weekday
600            600  1.2214  2.7023        17  6683426742    1    18        3
957            957  1.1832  2.6891        58  6683426742   10     2        5
4345          4345  1.1935  2.6550        11  6889790653    5    15        0
4735          4735  1.1452  2.6074        49  6822359752    6    23        1
5580          5580  1.0089  2.7287        19  1527921905    9    11        4
...            ...     ...     ...       ...         ...  ...   ...      ...
29100203  29100203  1.0129  2.6775        12  3312463746    1    10        3
29108443  29108443  1.1474  2.6840        36  3533177779    7    23        2
29109993  29109993  1.0240  2.7238        62  6424972551    8    15        3
29111539  29111539  1.2032  2.6796        87  3533177779    4     0        6
29112154  29112154  1.1070  2.5419       178  4932578245    8    23        3

[16918 rows x 8 columns]


In [59]:
y=data['place_id']
x=data.drop(['place_id'],axis=1)
x=x.drop(['row_id'],axis=1)
print(x)

               x       y  accuracy  day  hour  weekday
600       1.2214  2.7023        17    1    18        3
957       1.1832  2.6891        58   10     2        5
4345      1.1935  2.6550        11    5    15        0
4735      1.1452  2.6074        49    6    23        1
5580      1.0089  2.7287        19    9    11        4
...          ...     ...       ...  ...   ...      ...
29100203  1.0129  2.6775        12    1    10        3
29108443  1.1474  2.6840        36    7    23        2
29109993  1.0240  2.7238        62    8    15        3
29111539  1.2032  2.6796        87    4     0        6
29112154  1.1070  2.5419       178    8    23        3

[16918 rows x 6 columns]


In [61]:
print(y)

600         6683426742
957         6683426742
4345        6889790653
4735        6822359752
5580        1527921905
               ...    
29100203    3312463746
29108443    3533177779
29109993    6424972551
29111539    3533177779
29112154    4932578245
Name: place_id, Length: 16918, dtype: int64


In [77]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1)

std=StandardScaler()
x_train=std.fit_transform(x_train)
print(std.mean_)
print(std.var_)

[ 1.12295735  2.63237278 81.34938525  5.10064628 11.44293821  3.10135561]
[5.98489138e-03 4.86857391e-03 1.19597480e+04 7.32837915e+00
 4.83742660e+01 2.81838404e+00]


In [78]:
x_test=std.transform(x_test)
print(std.mean_)
print(std.var_)

[ 1.12295735  2.63237278 81.34938525  5.10064628 11.44293821  3.10135561]
[5.98489138e-03 4.86857391e-03 1.19597480e+04 7.32837915e+00
 4.83742660e+01 2.81838404e+00]


In [79]:
knn=KNeighborsClassifier(n_neighbors=8)
knn.fit(x_train,y_train)
y_predict=knn.predict(x_test)
print(y_predict)

[1913341282 1097200869 6097504486 ... 4932578245 6424972551 5095999304]


In [81]:
print("prediction accuracy is",knn.score(x_test,y_test))

prediction accuracy is 0.48156028368794324


In [88]:
param={'n_neighbors':[3,5,8,10,12,15]}
check=GridSearchCV(knn,param_grid=param,cv=3)
check.fit(x_train,y_train)
print(check.score(x_test,y_test))

C:\Users\gdmmx\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


0.48156028368794324


In [90]:
print(check.best_score_)
print(check.best_estimator_)
print(check.cv_results_)

0.462247649862548
KNeighborsClassifier(n_neighbors=8)
{'mean_fit_time': array([0.0315822 , 0.02127528, 0.01628963, 0.01652606, 0.01712799,
       0.01529837]), 'std_fit_time': array([0.00774028, 0.00248776, 0.00047126, 0.00057135, 0.00183907,
       0.00046573]), 'mean_score_time': array([0.50036979, 0.22074572, 0.23038514, 0.24565816, 0.23553403,
       0.26636799]), 'std_score_time': array([0.31641693, 0.01756589, 0.0126429 , 0.01860586, 0.0033018 ,
       0.02036987]), 'param_n_neighbors': masked_array(data=[3, 5, 8, 10, 12, 15],
             mask=[False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'n_neighbors': 3}, {'n_neighbors': 5}, {'n_neighbors': 8}, {'n_neighbors': 10}, {'n_neighbors': 12}, {'n_neighbors': 15}], 'split0_test_score': array([0.44468085, 0.4607565 , 0.46406619, 0.46170213, 0.45650118,
       0.45508274]), 'split1_test_score': array([0.43390873, 0.45660913, 0.46275715, 0.45542681, 0.45329865,
       0.44809648

In [94]:
print(len(news.data))
x_train,x_test,y_train,y_test=train_test_split(news.data,news.target,test_size=0.25,random_state=1)
tf=TfidfVectorizer()
x_train=tf.fit_transform(x_train)
print(len(tf.get_feature_names()))

18846
153196


In [96]:
x_test=tf.transform(x_test)
mlt=MultinomialNB(alpha=1.0)
mlt.fit(x_train,y_train)
print('prediction accuracy is',mlt.score(x_test,y_test))

AttributeError: lower not found

In [98]:
y_predict=mlt.predict(x_test)
print(classification_report(y_test,y_predict,target_names=news.target_names))

                          precision    recall  f1-score   support

             alt.atheism       0.91      0.77      0.83       199
           comp.graphics       0.83      0.79      0.81       242
 comp.os.ms-windows.misc       0.89      0.83      0.86       263
comp.sys.ibm.pc.hardware       0.80      0.83      0.81       262
   comp.sys.mac.hardware       0.90      0.88      0.89       234
          comp.windows.x       0.92      0.85      0.88       230
            misc.forsale       0.96      0.67      0.79       257
               rec.autos       0.90      0.87      0.88       265
         rec.motorcycles       0.90      0.95      0.92       251
      rec.sport.baseball       0.89      0.96      0.93       226
        rec.sport.hockey       0.95      0.98      0.96       262
               sci.crypt       0.76      0.97      0.85       257
         sci.electronics       0.84      0.80      0.82       229
                 sci.med       0.97      0.86      0.91       249
         

In [100]:
y_test1=np.where(y_test==5,1,0)
print(y_test1.sum())
y_predict1=np.where(y_predict==5,1,0)
print('AUC',roc_auc_score(y_test1,y_predict1))

230
AUC 0.924078924393225
