In [5]:
import numpy as np

t1=np.array(range(24)).reshape(6,4)
print(t1.dtype)
t2=t1/2
print(t2)
print(t2.dtype)
print(t1+2)
t3=np.array(range(100,124)).reshape(6,4)
print(t1+t3)

int32
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]
float64
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]


In [7]:
t1=np.array(range(24)).reshape(6,4)
t2=np.array(range(6)).reshape(6,1)
print(t1+t2)
t3=np.array(range(4)).reshape(1,4)
print(t1+t3)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]
 [25 26 27 28]]
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]
 [12 14 16 18]
 [16 18 20 22]
 [20 22 24 26]]


In [11]:
t1=np.array(range(12)).reshape(3,4)
print(t1)
print(np.sum(t1,axis=0))
print(np.sum(t1,axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]


In [14]:
t2=np.array(range(27)).reshape(3,3,3)
print(t2)
print('-'*50)
print(np.sum(t2,axis=0))
print(np.sum(t2,axis=1))
print(np.sum(t2,axis=2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------------------------------------------
[[27 30 33]
 [36 39 42]
 [45 48 51]]
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]


In [20]:
t=np.arange(24).reshape(4,6)
print(t[1])
print(t[1:3])
print(t[[0,2]])
print(t[:,1])
print(t[:,1:3])
print(t[:,[0,2]])
print(t[[1,1,2],[1,3,4]])

[ 6  7  8  9 10 11]
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]
[ 1  7 13 19]
[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]]
[[ 0  2]
 [ 6  8]
 [12 14]
 [18 20]]
[ 7  9 16]


In [24]:
t=np.arange(24).reshape(4,6)
t[1]=0
print(t)
t[:,1]=0
print(t)
t[1:3]=100
print(t)
t[:,1:3]=200
print(t)
t[t>99]=0
print(t)

[[ 0  1  2  3  4  5]
 [ 0  0  0  0  0  0]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  0  2  3  4  5]
 [ 0  0  0  0  0  0]
 [12  0 14 15 16 17]
 [18  0 20 21 22 23]]
[[  0   0   2   3   4   5]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [ 18   0  20  21  22  23]]
[[  0 200 200   3   4   5]
 [100 200 200 100 100 100]
 [100 200 200 100 100 100]
 [ 18 200 200  21  22  23]]
[[ 0  0  0  3  4  5]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18  0  0 21 22 23]]


In [30]:
t=np.arange(24).reshape(4,6)
print(t)
t[(t<2)|(t>6)]=0
print(t)
t=t.clip(1,4)
print(t)
result=np.where(t>3,True,False)
print(result)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 0 2 3 4 5]
 [6 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[1 1 2 3 4 4]
 [4 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[False False False False  True  True]
 [ True False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [37]:
a=np.arange(6).reshape(2,3)
print(a)
b=np.append(a,[6,7,8])
print(b)
c=np.append(a,[[6,7,8]],axis=0)
print(c)
d=np.append(a,[[6,7],[8,9]],axis=1)
print(d)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2 6 7]
 [3 4 5 8 9]]


In [67]:
a=np.arange(4).reshape(2,2)
print(a)
b=np.insert(a,3,[4,5])
print(b)
c=np.insert(a,0,[4,5],axis=0)
print(c)
d=np.insert(a,1,[4,5],axis=1)
print(d)

[[0 1]
 [2 3]]
[0 1 2 4 5 3]
[[4 5]
 [0 1]
 [2 3]]
[[0 4 1]
 [2 5 3]]


In [45]:
a=np.arange(12).reshape(3,4)
print(a)
b=np.delete(a,5)
print(b)
c=np.delete(a,1,axis=0)
print(c)
d=np.delete(a,1,axis=1)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [49]:
a=np.array([1,1,1,2,2,2,3,3,3,6,6,4,5,5])
b=np.unique(a)
print(b)
b,index=np.unique(a,return_index=True)
print(index)
b,index=np.unique(a,return_inverse=True)
print(index)
b,index=np.unique(a,return_counts=True)
print(index)

[1 2 3 4 5 6]
[ 0  3  6 11 12  9]
[0 0 0 1 1 1 2 2 2 5 5 3 4 4]
[3 3 3 1 2 2]


In [68]:
score=np.array([[80,85],[81,82],[100,99]])
print(np.max(score))
print(np.max(score,axis=0))
score=score.reshape(1,6)
print(np.maximum(score,90))
print(np.mean(score))
score=score.reshape(3,2)
print(np.max(score,axis=1))
print(np.mean(score,axis=1))
score1=score.cumsum(0)
print(score1)

100
[100  99]
[[ 90  90  90  90 100  99]]
87.83333333333333
[ 85  82 100]
[82.5 81.5 99.5]
[[ 80  85]
 [161 167]
 [261 266]]


In [64]:
score=np.array([[80,85],[81,82],[100,99]])
res=np.argmax(score,axis=1)
print(res)
res1=np.max(score)
print(res1)

[1 1 0]
100


In [73]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=1))
s=np.stack((a,b),axis=0)
print(s)
print(s.shape)
s1=np.stack((a,b),axis=1)
s2=np.stack((a,b),axis=2)
print(s1)
print(s2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [76]:
c1=[[1,2,3,4,5,6],[7,8,9,10,11,12]]
c2=[[13,14,15,16,17,18],[19,20,21,22,23,24]]
s=np.vstack((c1,c2))
print(s)
s1=np.hstack((c1,c2))
print(s1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[ 1  2  3  4  5  6 13 14 15 16 17 18]
 [ 7  8  9 10 11 12 19 20 21 22 23 24]]


In [85]:
a=np.arange(27).reshape(3,3,3)
b=np.split(a,3)
print(b)
c=np.split(a,3,axis=1)
print(c)
d=np.split(a,3,axis=2)
print(d)

[array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]]), array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]]), array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])]
[array([[[ 0,  1,  2]],

       [[ 9, 10, 11]],

       [[18, 19, 20]]]), array([[[ 3,  4,  5]],

       [[12, 13, 14]],

       [[21, 22, 23]]]), array([[[ 6,  7,  8]],

       [[15, 16, 17]],

       [[24, 25, 26]]])]
[array([[[ 0],
        [ 3],
        [ 6]],

       [[ 9],
        [12],
        [15]],

       [[18],
        [21],
        [24]]]), array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]],

       [[19],
        [22],
        [25]]]), array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]],

       [[20],
        [23],
        [26]]])]


In [82]:
a=10*np.random.random((2,6))
print(a)
print(np.vsplit(a,2))
print(np.hsplit(a,3))
#vsplit切断垂直轴

[[6.25175295 1.14051064 2.93767836 7.29648781 7.13345475 9.9677307 ]
 [6.14451011 6.68748378 0.32777224 5.49404476 0.65270323 1.13412885]]
[array([[6.25175295, 1.14051064, 2.93767836, 7.29648781, 7.13345475,
        9.9677307 ]]), array([[6.14451011, 6.68748378, 0.32777224, 5.49404476, 0.65270323,
        1.13412885]])]
[array([[6.25175295, 1.14051064],
       [6.14451011, 6.68748378]]), array([[2.93767836, 7.29648781],
       [0.32777224, 5.49404476]]), array([[7.13345475, 9.9677307 ],
       [0.65270323, 1.13412885]])]


In [93]:
a=np.inf
b=np.nan
print(type(a))
print(type(b))
t=np.arange(24,dtype=np.float32).reshape(4,6)
print(t)
t[3,4]=np.nan
print(t)
print(np.count_nonzero(t))
print(np.nan==np.nan)
print(np.count_nonzero(t!=t))

<class 'float'>
<class 'float'>
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. nan 23.]]
23
False
1


In [99]:
t=np.arange(24).reshape(4,6).astype(float)
t[1,3:]=np.nan
print(t)
t[t==np.nan]=np.mean(t)
print(t)
for i in range(t.shape[1]):
    temp_col=t[:,i]
    zero_count=np.count_nonzero(temp_col!=temp_col)
    if zero_count!=0:
        temp_col1=temp_col[temp_col==temp_col]
        temp_col[temp_col!=temp_col]=np.mean(temp_col1)
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


In [4]:
import numpy as np
t=np.arange(24).reshape(4,6).astype(float)
print(t.T)
print(np.transpose(t))
print(t.shape)

[[ 0.  6. 12. 18.]
 [ 1.  7. 13. 19.]
 [ 2.  8. 14. 20.]
 [ 3.  9. 15. 21.]
 [ 4. 10. 16. 22.]
 [ 5. 11. 17. 23.]]
[[ 0.  6. 12. 18.]
 [ 1.  7. 13. 19.]
 [ 2.  8. 14. 20.]
 [ 3.  9. 15. 21.]
 [ 4. 10. 16. 22.]
 [ 5. 11. 17. 23.]]
(4, 6)


In [12]:
t=np.ones((3,4,5))
print(t)

t=t.swapaxes(1,0)
print(t)

t=np.ones((3,4,5,6))
t=np.rollaxis(t,2,0)
print(t.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(5, 3, 4, 6)
