In [5]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.preprocessing import  MinMaxScaler,StandardScaler
from sklearn.feature_selection import  VarianceThreshold
from sklearn.decomposition import PCA
import jieba
import numpy as np
from sklearn.impute import SimpleImputer

In [8]:
def dictvec():
    dict=DictVectorizer(sparse=False)
    data=dict.fit_transform([{'city': '北京', 'temperature': 30},
                               {'city': '上海', 'temperature': 40},
                               {'city': '深圳', 'temperature': 35}])
    print(data)
    print(dict.get_feature_names())
    print(dict.inverse_transform(data))
    return None

dictvec()

[[ 0.  1.  0. 30.]
 [ 1.  0.  0. 40.]
 [ 0.  0.  1. 35.]]
['city=上海', 'city=北京', 'city=深圳', 'temperature']
[{'city=北京': 1.0, 'temperature': 30.0}, {'city=上海': 1.0, 'temperature': 40.0}, {'city=深圳': 1.0, 'temperature': 35.0}]
