In [2]:
import pandas as pd
import numpy as np
import random


In [9]:
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data1' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'key': ['a', 'b' ,'d'],
                        'data2' : np.random.randint(0,10,3)})
print(df_obj1)
print(" "*50)
print(df_obj2)
#两个df中都出现的key才会有，形成一个key两个数据
# print(pd.merge(df_obj1,df_obj2))

#行数为最少的那行，只是直接拼到右边，多余的行不管了
# print(pd.merge(df_obj1,df_obj2,left_index=True,right_index=True))

#和情况1一样
# print(pd.merge(df_obj1,df_obj2,on='key'))

  key  data1
0   b      4
1   b      2
2   a      8
3   c      3
4   a      1
5   a      8
6   b      5
                                                  
  key  data2
0   a      9
1   b      3
2   d      6
  key  data1  data2
0   b      4      3
1   b      2      3
2   b      5      3
3   a      8      9
4   a      1      9
5   a      8      9
  key  data1  data2
0   b      4      3
1   b      2      3
2   b      5      3
3   a      8      9
4   a      1      9
5   a      8      9


In [15]:
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                        'data' : np.random.randint(0,10,3)})
df_obj1 = df_obj1.rename(columns={'key':'key1'})
df_obj2 = df_obj2.rename(columns={'key':'key2'})
print(df_obj1)
print(df_obj2)

#拿相同的列名链接 有不同的元素
# print(pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2'))

#所有元素都会有 没有对应的另外用nan
# pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='outer')

# 按第一个df的列明连 是全外连接的一部分
# print(pd.merge(df_obj1, df_obj2, left_on='key1', right_on='key2', how='left'))

  key1  data1
0    b      4
1    b      2
2    a      8
3    c      3
4    a      1
5    a      8
6    b      5
  key2  data2
0    a      9
1    b      3
2    d      6


KeyError: 'key'

In [16]:
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                        'data' : np.random.randint(0,10,3)})
print(pd.merge(df_obj1, df_obj2, on='key', suffixes=('_left', '_right')))

  key  data_left  data_right
0   b          0           3
1   b          7           3
2   b          6           3
3   a          4           7
4   a          2           7
5   a          4           7


In [18]:
df_obj1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                        'data1' : np.random.randint(0,10,7)})
df_obj2 = pd.DataFrame({'data2' : np.random.randint(0,10,3)}, index=['a', 'b', 'd'])
print(df_obj1)
print(df_obj2)
print(pd.merge(df_obj1, df_obj2, left_on='key', right_index=True))
print(pd.merge(df_obj2,df_obj1, left_index=True, right_on='key'))

  key  data1
0   b      4
1   b      9
2   a      2
3   c      3
4   a      4
5   a      1
6   b      5
   data2
a      6
b      2
d      7
  key  data1  data2
0   b      4      2
1   b      9      2
6   b      5      2
2   a      2      6
4   a      4      6
5   a      1      6
   data2 key  data1
2      6   a      2
4      6   a      4
5      6   a      1
0      2   b      4
1      2   b      9
6      2   b      5


In [19]:
arr1 = np.random.randint(0, 10, (3, 4))
arr2 = np.random.randint(0, 10, (3, 4))

print(arr1)
print(arr2)
print(np.concatenate([arr1,arr2]))
print(np.concatenate([arr1,arr2],axis=1))

[[1 7 8 5]
 [4 9 2 3]
 [3 2 9 5]]
[[7 5 6 2]
 [2 6 0 1]
 [7 6 9 1]]
[[1 7 8 5]
 [4 9 2 3]
 [3 2 9 5]
 [7 5 6 2]
 [2 6 0 1]
 [7 6 9 1]]
[[1 7 8 5 7 5 6 2]
 [4 9 2 3 2 6 0 1]
 [3 2 9 5 7 6 9 1]]


In [21]:
ser_obj1=pd.Series(np.random.randint(0,10,5),index=range(0,5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index=range(5,9))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index=range(9,12))

print(ser_obj1)
print(ser_obj2)
print(ser_obj3)
print(' '*50)
# 直接往下拼接
# print(pd.concat([ser_obj1,ser_obj2,ser_obj3]))
#横着拼接 没对应的用nan
print(pd.concat([ser_obj1,ser_obj2,ser_obj3],axis=1))

0    8
1    1
2    3
3    1
4    6
dtype: int32
5    3
6    6
7    4
8    7
dtype: int32
9     0
10    4
11    5
dtype: int32
                                                  
      0    1    2
0   8.0  NaN  NaN
1   1.0  NaN  NaN
2   3.0  NaN  NaN
3   1.0  NaN  NaN
4   6.0  NaN  NaN
5   NaN  3.0  NaN
6   NaN  6.0  NaN
7   NaN  4.0  NaN
8   NaN  7.0  NaN
9   NaN  NaN  0.0
10  NaN  NaN  4.0
11  NaN  NaN  5.0
Empty DataFrame
Columns: [0, 1, 2]
Index: []


In [23]:
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index=range(5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index=range(4))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index=range(3))

print(ser_obj1)
print(ser_obj2)
print(ser_obj3)
#有重复索引 inner join 没有对应的不出现
print(pd.concat([ser_obj1,ser_obj2,ser_obj3],axis=1,join='inner'))
print(pd.concat([ser_obj1, ser_obj2, ser_obj3]))

0    3
1    5
2    5
3    7
4    5
dtype: int32
0    9
1    5
2    6
3    9
dtype: int32
0    0
1    7
2    0
dtype: int32
   0  1  2
0  3  9  0
1  5  5  7
2  5  6  0
0    3
1    5
2    5
3    7
4    5
0    9
1    5
2    6
3    9
0    0
1    7
2    0
dtype: int32


In [25]:
df_obj1 = pd.DataFrame(np.random.randint(0, 10, (3, 2)), index=['a', 'b', 'c'],
                       columns=['A', 'B'])
df_obj2 = pd.DataFrame(np.random.randint(0, 10, (2, 2)), index=['a', 'b'],
                       columns=['A', 'B'])
print(df_obj1)
print(df_obj2)
#与series同理
print(pd.concat([df_obj1, df_obj2]))
print(pd.concat([df_obj1, df_obj2], axis=1))

   A  B
a  5  7
b  7  9
c  0  4
   A  B
a  8  5
b  0  0
   A  B
a  5  7
b  7  9
c  0  4
a  8  5
b  0  0
   A  B    A    B
a  5  7  8.0  5.0
b  7  9  0.0  0.0
c  0  4  NaN  NaN


In [28]:
df_obj = pd.DataFrame(np.random.randint(0,10, (5,2)), columns=['data1', 'data2'])
print(df_obj)
stacked = df_obj.stack()
print(stacked)

   data1  data2
0      8      1
1      8      7
2      5      8
3      6      2
4      1      1
0  data1    8
   data2    1
1  data1    8
   data2    7
2  data1    5
   data2    8
3  data1    6
   data2    2
4  data1    1
   data2    1
dtype: int32


KeyError: 'Requested level (data1) does not match index name (None)'

In [31]:
index1=pd.MultiIndex.from_arrays([['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c', 'd', 'd', 'd'],
                [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]],names=['cloth','size'])
df=pd.DataFrame(np.arange(24).reshape(12,2),index=index1,columns=['data1','data2'])
print(df)
# 默认内层索引，level=-1
df_unstacked=df.unstack()
print(df_unstacked)
df1_unstacked=df.unstack(level='cloth')
print(df1_unstacked)

            data1  data2
cloth size              
a     0         0      1
      1         2      3
      2         4      5
b     0         6      7
      1         8      9
      2        10     11
c     0        12     13
      1        14     15
      2        16     17
d     0        18     19
      1        20     21
      2        22     23
      data1         data2        
size      0   1   2     0   1   2
cloth                            
a         0   2   4     1   3   5
b         6   8  10     7   9  11
c        12  14  16    13  15  17
d        18  20  22    19  21  23
      data1             data2            
cloth     a   b   c   d     a   b   c   d
size                                     
0         0   6  12  18     1   7  13  19
1         2   8  14  20     3   9  15  21
2         4  10  16  22     5  11  17  23


In [46]:
df.obj=pd.DataFrame({'data1':['a']*4+['b']*4,
                    'data2': np.random.randint(0,4,8)})
print(df_obj)
#返回TF矩阵
print(df_obj.duplicated())
print(df_obj[~df_obj.duplicated()])
print(df_obj.duplicated('data2'))

  data1  data2
0     a      1
1     a      1
2     a      2
3     a      0
4     b      1
5     b      3
6     b      1
7     b      0
0    False
1     True
2    False
3    False
4    False
5    False
6     True
7    False
dtype: bool
  data1  data2
0     a      1
2     a      2
3     a      0
4     b      1
5     b      3
7     b      0
0    False
1     True
2    False
3    False
4     True
5    False
6     True
7     True
dtype: bool


In [49]:
df_obj1 = pd.DataFrame({'data1' :[np.nan] * 4,
                       'data2' :list('1235')})
print(df_obj1)
print(df_obj1.duplicated('data1'))
df_obj1.drop_duplicates('data1',inplace=True)
print(df_obj1)

   data1 data2
0    NaN     1
1    NaN     2
2    NaN     3
3    NaN     5
0    False
1     True
2     True
3     True
dtype: bool
   data1 data2
0    NaN     1


In [59]:
df1=pd.DataFrame({'data1':[3,3,3,5,5,5],'data2':np.random.randint(1,100,6)})
print(df1)
df2=df1.groupby('data1').transform(np.sum)
print(df2)
df3=df1.groupby('data1').apply(np.mean)
print(df3)

   data1  data2
0      3     92
1      3     71
2      3     89
3      5     81
4      5     60
5      5     46
   data2
0    252
1    252
2    252
3    187
4    187
5    187
       data1      data2
data1                  
3        3.0  84.000000
5        5.0  62.333333
