In [2]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.feature_selection import VarianceThreshold
from sklearn.decomposition import PCA
import jieba
import numpy as np
from sklearn.impute import SimpleImputer

In [14]:
def couvec():
    #实例化类
    vector=CountVectorizer(min_df=2)
    #res是一个稀疏矩阵的表达
    res=vector.fit_transform([
        "i like you",
        "you like me",
        "i like you,and you?"
    ])
    print(vector.get_feature_names())
    print(res)
    print(type(res))
    #稀疏矩阵toarray后变为正常矩阵
    print(res.toarray())
    #不会返回原句而是特征单词
    print(vector.inverse_transform(res))
couvec()

['like', 'you']
  (0, 0)	1
  (0, 1)	1
  (1, 0)	1
  (1, 1)	1
  (2, 0)	1
  (2, 1)	2
<class 'scipy.sparse.csr.csr_matrix'>
[[1 1]
 [1 1]
 [1 2]]
[array(['like', 'you'], dtype='<U4'), array(['like', 'you'], dtype='<U4'), array(['like', 'you'], dtype='<U4')]


In [5]:
def countvec():
    cv=CountVectorizer()
    #本身是矩阵
    character=cv.fit_transform(['不要回答！不要回答！ 不要回 答！don‘t answer！'])
    print(cv.get_feature_names())
    print(character)
    print((character.toarray()))
    return None
countvec()

['answer', 'don', '不要回', '不要回答']
  (0, 3)	2
  (0, 2)	1
  (0, 1)	1
  (0, 0)	1
[[1 1 1 2]]


In [11]:
def cutchar():
    character1=jieba.cut("我们只是微小尘埃中的一员")
    character2=jieba.cut("明天的事就留到明天去做吧")
    character3=jieba.cut("金风玉露一相逢,便胜却人间无数")
    # character1是一个生成器
    print(type(character1))
    #用list将生成器转为列表
    content1=list(character1)
    content2=list(character2)
    content3=list(character3)
    print(content1,content2,content3)
    #变为字符串
    t1=' '.join(content1)
    t2=' '.join(content2)
    t3=' '.join(content3)
    print(type(t1))
    return t1,t2,t3
s=cutchar()
print(s)
print(type(s))

<class 'generator'>
['我们', '只是', '微小', '尘埃', '中', '的', '一员'] ['明天', '的', '事', '就', '留到', '明天', '去', '做', '吧'] ['金风玉露', '一', '相逢', ',', '便胜', '却', '人间', '无数']
<class 'str'>
('我们 只是 微小 尘埃 中 的 一员', '明天 的 事 就 留到 明天 去 做 吧', '金风玉露 一 相逢 , 便胜 却 人间 无数')
<class 'tuple'>


In [16]:
def charvec():
    c1,c2,c3=cutchar()
    cv=CountVectorizer()
    data=cv.fit_transform([c1,c2,c3])
    #%%用实例化的类来得到特征各项
    print(cv.get_feature_names())
    # print(cv.__getattribute__())
    print(data.toarray())
    return None
charvec()

<class 'generator'>
['我们', '只是', '微小', '尘埃', '中', '的', '一员'] ['明天', '的', '事', '就', '留到', '明天', '去', '做', '吧'] ['金风玉露', '一', '相逢', ',', '便胜', '却', '人间', '无数']
<class 'str'>
['一员', '人间', '便胜', '只是', '尘埃', '微小', '我们', '无数', '明天', '留到', '相逢', '金风玉露']
[[1 0 0 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 1 0 0]
 [0 1 1 0 0 0 0 1 0 0 1 1]]


In [21]:
def tfidfvec():
    c1,c2,c3=cutchar()
    tf=TfidfVectorizer()
    data=tf.fit_transform([c1,c2,c3])
    print(tf.get_feature_names())
    print(type(data))
    print(data)
    print(data.toarray())
tfidfvec()

<class 'generator'>
['我们', '只是', '微小', '尘埃', '中', '的', '一员'] ['明天', '的', '事', '就', '留到', '明天', '去', '做', '吧'] ['金风玉露', '一', '相逢', ',', '便胜', '却', '人间', '无数']
<class 'str'>
['一员', '人间', '便胜', '只是', '尘埃', '微小', '我们', '无数', '明天', '留到', '相逢', '金风玉露']
<class 'scipy.sparse.csr.csr_matrix'>
  (0, 0)	0.4472135954999579
  (0, 4)	0.4472135954999579
  (0, 5)	0.4472135954999579
  (0, 3)	0.4472135954999579
  (0, 6)	0.4472135954999579
  (1, 9)	0.4472135954999579
  (1, 8)	0.8944271909999159
  (2, 7)	0.4472135954999579
  (2, 1)	0.4472135954999579
  (2, 2)	0.4472135954999579
  (2, 10)	0.4472135954999579
  (2, 11)	0.4472135954999579
[[0.4472136  0.         0.         0.4472136  0.4472136  0.4472136
  0.4472136  0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.89442719 0.4472136  0.         0.        ]
 [0.         0.4472136  0.4472136  0.         0.         0.
  0.         0.4472136  0.         0.         0.4472

In [23]:
def toone():
    mm=MinMaxScaler(feature_range=(-1,1))
    data=mm.fit_transform([[90, 2, 10, 40], [60, 4, 15, 45], [75, 3, 13, 46]] )
    print(data)
    return None
toone()

[[ 1.         -1.         -1.         -1.        ]
 [-1.          1.          1.          0.66666667]
 [ 0.          0.          0.2         1.        ]]


In [27]:
def standard():
    std=StandardScaler()
    data=std.fit_transform([[1., -1., 3.], [2., 4., 2.], [4., 6., -1.]])
    print(data)
    #用实例化的类来取而不是数据本身
    #转成的data方差为1均值为0
    print(std.mean_)
    print(std.var_)
    print(std.n_samples_seen_)
    data1=std.fit_transform([[-1.06904497,-1.35873244,0.98058068],
    [-0.26726124,0.33968311,0.39223227],
    [ 1.33630621,1.01904933,-1.37281295]])
    print(std.mean_)
    print(std.var_)
standard()

[[-1.06904497 -1.35873244  0.98058068]
 [-0.26726124  0.33968311  0.39223227]
 [ 1.33630621  1.01904933 -1.37281295]]
[2.33333333 3.         1.33333333]
[1.55555556 8.66666667 2.88888889]
3
[0. 0. 0.]
[1.         1.         1.00000001]


In [29]:
def fillmissing():
    fm=SimpleImputer(missing_values=np.nan,strategy='median')
    data=fm.fit_transform([[1, 2], [np.nan, 3], [7, 6], [3, 2]])
    print(data)
fillmissing()


[[1. 2.]
 [3. 3.]
 [7. 6.]
 [3. 2.]]


In [32]:
def var_low_out():
    var=VarianceThreshold(threshold=0)
    data=var.fit_transform([[0, 2, 0, 3],
                              [0, 1, 4, 3],
                              [1, 1, 1, 3]])
    print(data)
    print(var.get_support())
var_low_out()

[[0 2 0]
 [0 1 4]
 [1 1 1]]
[ True  True  True False]
