In [ ]:
import time
import random
import numpy as np
a=[random.random() for i in range(1000000)]
t1=time.time()
sum1=sum(a)
t2=time.time()
b=np.array(a)
t3=time.time()
sum2=np.sum(b)
t4=time.time()
print(t2-t1,t4-t3)

In [9]:
list1=[1,2,3]
a=np.array(list1)
print(a)
list2=[[1,2,3],[4,5,6]]
b=np.array(list2)
print(b)
print(b.shape)
print(b.ndim)
print(b.size)

c=b.reshape(3,2)
print(c)
d=c.flatten()
print(d)

e=np.arange(24).reshape(4,6)
print(e)

print(e.tolist())

[1 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


[[0, 1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10, 11],
 [12, 13, 14, 15, 16, 17],
 [18, 19, 20, 21, 22, 23]]

In [14]:
f=np.array([1,2,3,4,5],dtype=np.int16)
print(f.dtype)
print(f.itemsize)#字节数

f1=f.astype(np.int32)
print(f1.dtype)
print(f1.itemsize)



int16
2
int32
4
float64
8


C:\Users\gdmmx\AppData\Local\Temp/ipykernel_27172/1073560227.py:9: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  f2=f.astype(np.float)
